const ROLES = {
  PRESIDENT: "PRESIDENT",
  GENSEC_SCITECH: "GENSEC_SCITECH",
  GENSEC_ACADEMIC: "GENSEC_ACADEMIC",
  GENSEC_CULTURAL: "GENSEC_CULTURAL",
  GENSEC_SPORTS: "GENSEC_SPORTS",
  CLUB_COORDINATOR: "CLUB_COORDINATOR",
  STUDENT: "STUDENT",
};

const ROLE_GROUPS = {
  ADMIN: [
    ROLES.PRESIDENT,
    ROLES.GENSEC_SCITECH,
    ROLES.GENSEC_ACADEMIC,
    ROLES.GENSEC_CULTURAL,
    ROLES.GENSEC_SPORTS,
    ROLES.CLUB_COORDINATOR,
  ],
  GENSECS: [
    ROLES.GENSEC_SCITECH,
    ROLES.GENSEC_ACADEMIC,
    ROLES.GENSEC_CULTURAL,
    ROLES.GENSEC_SPORTS,
  ],
  COORDINATORS: [
    ROLES.CLUB_COORDINATOR,
  ],
};

module.exports = { ROLES, ROLE_GROUPS };
