# -------- STAGE 1: Builder --------
    FROM node:22-alpine AS builder

    WORKDIR /app
    
    # Install dependencies
    COPY package*.json ./
    RUN npm ci --omit=dev && npm cache clean --force
    
    # Copy the application code
    COPY . .
    
    # -------- STAGE 2: Production --------
    FROM node:22-alpine
    
    ENV NODE_ENV=production
    
    # Create non-root user
    RUN addgroup -S appgroup && adduser -S appuser -G appgroup
    
    WORKDIR /app
    
    # Copy only necessary files from builder
    COPY --from=builder /app /app
    
    USER appuser
    
    EXPOSE 3000
    
    CMD ["node", "index.js"]
    